### ISSUE TITLE
fix/ 메타데이터 수정

### ISSUE THREAD

**Issue by JuhyeokC** [team-final/albaform#19]
## 어떤 기능인가요?
> 추가하려는 기능에 대해 간결하게 설명해주세요
- 메타데이터를 수정하는 작업입니다.

![Image](https://github.com/user-attachments/assets/47259c66-1140-4064-89d4-ba82f943a9a4)

## 작업 상세 내용
- [x] metadata.title
- [x] metadata.description
- [x] html lang

## 팀원들에게 알리고 싶다
- 파일위치는 `@app/layout.tsx` 입니다.
- 

## 참고할만한 자료(선택)
- 
-

**Comment by JiinSeok** [comment]
@JuhyeokC 이미 완료된 것으로 기억하는데 처리한 PR 언급하고 닫으면 어떨까요?!

**Comment by JiinSeok** [comment]
#41 에서 처리

**Comment by JiinSeok** [comment]
@JuhyeokC 대단하네요 처음 알았습니다 
> metadata 객체는 Next.js에서 페이지의 메타 정보를 정의하는 데 사용됩니다. 이 정보는 HTML 문서의 <head> 섹션에 자동으로 삽입되어 SEO(검색 엔진 최적화)나 소셜 미디어 미리보기 등에 활용됩니다.
