### ISSUE TITLE
fix/RootHeader 관련 컴포넌트 구조 수정

### ISSUE THREAD

**Issue by JuhyeokC** [team-final/albaform#84]
## 어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

📁 GNB
  ⌙ index.tsx (RootHeader)
  ⌙ 📁 Logo (RootLogo)
  ⌙ 📁 Nav (RootNav)
  ⌙ 📁 Menu (GNB)
  ⌙ 📁 AuthMenu (AuthSpecificMenu)

Button 관련 컴포넌트 폴더
Button 디렉토리에 옮기기

## 작업 상세 내용

- [ ] GNB 디렉토리 생성
- [ ] GNB 관련 컴포넌트 경로 수정
- [ ] GNB > Menu 에 임시 페이지 링크 생성
- [ ] Button 관련 컴포넌트 경로 수정

## 팀원들에게 알리고 싶다

-
-

## 참고할만한 자료(선택)

-
-

**Comment by JuhyeokC** [comment]
@JiinSeok 컨펌 해주십셔 원하시는 대로 하겠나이다

**Comment by JiinSeok** [comment]
@JuhyeokC 답이 늦었습니다..! 확인 부탁드립니다!

1. 줄임말이 없는 GlobalNavigationBar 어떨까요?
2. Nav와 Menu가 비슷해서, 확실히 구별되는 Menu와 SideBar가 어떨까요?
3. 클릭할 수 없게 할 것이므로, UserTypeIndicator 어떨까요? (다른 페이지에서도 보여주도록 확장할 수도 있고)

📁 GlobalNavigationBar
⌙ index.tsx (RootHeader)
⌙ 📁 Logo (RootLogo)
⌙ 📁 Menu (RootNav)
⌙ 📁 SideBar (GNB)
⌙ 📁 UserTypeIndicator (AuthSpecificMenu)

**Comment by JuhyeokC** [comment]
> [@JuhyeokC](https://github.com/JuhyeokC) 답이 늦었습니다..! 확인 부탁드립니다!
> 
> 1. Component/Component.tsx로 컴포넌트 파일 이름 정했던 것 같습니다!
> 2. 줄임말이 없는 GlobalNavigationBar 어떨까요?
> 3. Nav와 Menu가 비슷해서, 확실히 구별되는 Menu와 SideBar가 어떨까요?
> 4. 클릭할 수 없게 할 것이므로, UserTypeIndicator 어떨까요? (다른 페이지에서도 보여주도록 확장할 수도 있고)
> 
> 📁 GlobalNavigationBar ⌙ GlobalNavigationBar.tsx (RootHeader) ⌙ 📁 Logo (RootLogo) ⌙ 📁 Menu (RootNav) ⌙ 📁 SideBar (GNB) ⌙ 📁 UserTypeIndicator (AuthSpecificMenu)

좋습니다~
